### ISSUE TITLE
Installing xgboost==6.0 fails on Mac OS X

### ISSUE THREAD

**Issue by FilippoBovo** [SamLubbers/datascience_blogfinder#6]
`xgboost==6.0` does not exists. Replacing it with versions `0.6a1` or `0.6a2` does not work either as it requires `gcc 5` that is not installed with XCode on Mac. So, I reverted back to version `0.4a30` which install correctly.

**Comment by SamLubbers** [comment]
I am surprised by this behaviour as I am using a Mac myself and I simply created the requirements.txt file using the command `pip freeze > requirements.txt` from the virtual environment from which I was running the application.

I will review the issue and solve it asap.

**Comment by SamLubbers** [comment]
After examining the issue I have found out that `xgboost==0.6` is a transitive dependency to the scikit-learn library. I will fix the issue by removing `xgboost==0.6` from `requirements.txt` and have scikit-learn install it automatically when itself is installed.
